name: Özellik önerisi
description: Yeni bir fikir veya iyileştirme önerin
labels: ["öneri"]
body:
  - type: textarea
    id: sorun
    attributes:
      label: "Hangi sorunu çözüyor?"
    validations:
      required: true
  - type: textarea
    id: oneri
    attributes:
      label: "Önerdiğiniz çözüm"
  - type: textarea
    id: alternatif
    attributes:
      label: "Düşündüğünüz alternatifler"
